---

- name: create wal2json dir
  file:
    dest: "{{ wal2json_path }}"
    state: directory
    owner: root
    mode: 0700
  become: yes

- name: fetch wal2json
  git:
    repo: https://github.com/eulerto/wal2json.git
    dest: "{{ wal2json_path }}"
    version:  "{{ wal2json_git_version }}"
    depth: 1
  become: yes

- name: install dependencies
  apt:
    name: [make, gcc, "postgresql-server-dev-{{ postgresql_version }}"]
  become: yes

- name: check module has been built
  stat:
    path: "/usr/lib/postgresql/{{ postgresql_version }}/lib/wal2json.so"
  ignore_errors: yes
  register: wal2json_module

- name: build wal2json
  make:
    chdir: "{{ wal2json_path }}"
  environment:
    PATH: "$PATH:/usr/bin:/usr/local/bin:{{ postgresql_bin_path }}"
    USE_PGXS: 1
  become: yes
  when: not wal2json_module.stat.exists

- name: install wal2json
  make:
    chdir: "{{ wal2json_path }}"
    target: install
  environment:
    PATH: "$PATH:/usr/bin:/usr/local/bin:{{ postgresql_bin_path }}"
    USE_PGXS: 1
  become: yes
  when: not wal2json_module.stat.exists

- name: ensure postgres conf.d directory exists
  file:
    dest: "{{ postgresql_config_path }}/conf.d"
    state: directory
    owner: postgres
    group: postgres
    mode: 0740
  become: yes

- name: add postgres wal2json config
  template:
    src: wal2json.conf.j2
    dest: "{{ postgresql_config_path }}/conf.d/wal2json.conf"
    owner: postgres
    group: postgres
    mode: 0644
  become: yes
  notify: restart postgres
