---

- name: install wal2json from postgresql repo
  include_tasks: install.yml
  when: not wal2json_build_from_source

- name: build wal2json from source
  include_tasks: build.yml
  when: wal2json_build_from_source

- name: ensure postgres conf.d directory exists
  file:
    dest: "{{ postgresql_config_path }}/conf.d"
    state: directory
    owner: postgres
    group: postgres
    mode: 0740
  become: yes

- name: add postgres wal2json config
  template:
    src: wal2json.conf.j2
    dest: "{{ postgresql_config_path }}/conf.d/wal2json.conf"
    owner: postgres
    group: postgres
    mode: 0644
  become: yes
  notify: restart postgres
